// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Data;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(FertilizerCalculatorDbContext))]
    partial class FertilizerCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.FertilizerCalculator.CropRequirements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrowthStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("K")
                        .HasColumnType("double precision");

                    b.Property<double>("N")
                        .HasColumnType("double precision");

                    b.Property<double>("P")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CropRequirements");
                });

            modelBuilder.Entity("Domain.Models.FertilizerCalculator.Fertilizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CostPerKg")
                        .HasColumnType("double precision");

                    b.Property<double>("KPct")
                        .HasColumnType("double precision");

                    b.Property<double>("NPct")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PPct")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Fertilizers");
                });

            modelBuilder.Entity("Domain.Models.FertilizerCalculator.SoilMultiplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("KMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("NMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("PMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoilMultiplier");
                });
#pragma warning restore 612, 618
        }
    }
}
