<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AgroBackEnd\**" />
    <Compile Remove="Domain\**" />
    <Compile Remove="Repository\**" />
    <Compile Remove="Service\**" />
    <Compile Remove="tools\**" />
    <Content Remove="AgroBackEnd\**" />
    <Content Remove="Domain\**" />
    <Content Remove="Repository\**" />
    <Content Remove="Service\**" />
    <Content Remove="tools\**" />
    <EmbeddedResource Remove="AgroBackEnd\**" />
    <EmbeddedResource Remove="Domain\**" />
    <EmbeddedResource Remove="Repository\**" />
    <EmbeddedResource Remove="Service\**" />
    <EmbeddedResource Remove="tools\**" />
    <None Remove="AgroBackEnd\**" />
    <None Remove="Domain\**" />
    <None Remove="Repository\**" />
    <None Remove="Service\**" />
    <None Remove="tools\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Domain\Domain.csproj" />
    <ProjectReference Include="Repository\Repository.csproj" />
    <ProjectReference Include="Service\Service.csproj" />
  </ItemGroup>

</Project>
